'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { Loader2, Save, Sparkles, Upload } from 'lucide-react';
import { ManifestHostingFooter } from '@/components/domain-profile/ManifestHostingPanel';
import { toast } from '@/components/ui/sonner';
import { Button } from '@/components/ui/button';
import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from '@/components/ui/resizable';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { useProject } from '@/components/projects/ProjectProvider';
import { resolvePromptIdFromSearchParams } from '@/lib/ai-visibility/gap-fill';
import {
  consumeAutoGenerateIntent,
  consumeVisibilityPrefill,
} from '@/lib/ai-visibility/prefill';
import type { VisibilityActionPayload } from '@/lib/ai-visibility/types';
import {
  buildLiveManifestPreview,
  useGapAnalysisStore,
} from '@/lib/article-studio/gap-analysis-store';
import {
  AEO_EXTRACT_CREDIT_COST,
  type AutoGenerateGapArticle,
} from '@/lib/article-studio/gap-analysis-types';
import { useWorkspaceDomainPreview } from '@/hooks/useWorkspaceDomainPreview';
import { useVisibilityGap } from '@/hooks/useVisibilityGap';
import GapAnalysisRichTextEditor from './GapAnalysisRichTextEditor';
import GapAnalysisMetadataPanel from './GapAnalysisMetadataPanel';
import LiveManifestPreview from './LiveManifestPreview';
import GapAnalysisAutoGenerateSkeleton from './GapAnalysisAutoGenerateSkeleton';
import { cn } from '@/lib/utils';

type GapAnalysisWorkspaceProps = {
  briefId?: number | null;
  articleId?: number | null;
  onPublished?: (payload: { slug: string; articleUrl: string }) => void;
  onDraftSaved?: () => void;
};

export default function GapAnalysisWorkspace({
  briefId,
  articleId,
  onPublished,
  onDraftSaved,
}: GapAnalysisWorkspaceProps) {
  const router = useRouter();
  const searchParams = useSearchParams();
  const { activeProjectId } = useProject();
  const [leftTab, setLeftTab] = useState<'draft' | 'metadata'>('draft');
  const prefillConsumedRef = useRef(false);
  const visibilityPrefillRef = useRef<VisibilityActionPayload | null>(null);
  const lastHydratedPromptIdRef = useRef<string | null>(null);
  const autoGenerateStartedRef = useRef(false);
  const autoGenerateSucceededRef = useRef(false);

  const autoGenerateFromUrl = searchParams.get('autoGenerate') === '1';
  const autoGenerateFromSessionRef = useRef<boolean | null>(null);
  if (autoGenerateFromSessionRef.current === null) {
    autoGenerateFromSessionRef.current =
      autoGenerateFromUrl || consumeAutoGenerateIntent();
  }
  const autoGenerate = autoGenerateFromSessionRef.current;
  const [autoGenerateDone, setAutoGenerateDone] = useState(false);

  const promptIdFromUrl = useMemo(
    () => resolvePromptIdFromSearchParams(searchParams),
    [searchParams]
  );
  const projectIdFromUrl = searchParams.get('projectId');

  const [resolvedPromptId, setResolvedPromptId] = useState<string | null>(promptIdFromUrl);
  const [prefillProjectId, setPrefillProjectId] = useState<string | null>(null);

  const effectiveProjectId =
    activeProjectId || projectIdFromUrl || prefillProjectId || null;

  useEffect(() => {
    if (promptIdFromUrl) {
      setResolvedPromptId(promptIdFromUrl);
      return;
    }

    if (prefillConsumedRef.current) {
      return;
    }

    const prefill = consumeVisibilityPrefill();
    prefillConsumedRef.current = true;
    visibilityPrefillRef.current = prefill;
    if (prefill?.projectId) {
      setPrefillProjectId(prefill.projectId);
    }
    if (prefill?.promptId) {
      setResolvedPromptId(prefill.promptId);
    }
  }, [promptIdFromUrl]);

  const {
    data: gapData,
    isLoading: isGapLoading,
    isError: isGapError,
    error: gapError,
  } = useVisibilityGap(resolvedPromptId, effectiveProjectId);

  const editorContent = useGapAnalysisStore(state => state.editorContent);
  const metadata = useGapAnalysisStore(state => state.metadata);
  const isPublishing = useGapAnalysisStore(state => state.isPublishing);
  const publishError = useGapAnalysisStore(state => state.publishError);
  const sourceRoute = useGapAnalysisStore(state => state.sourceRoute);
  const sourceClusters = useGapAnalysisStore(state => state.sourceClusters);
  const linkedPromptId = useGapAnalysisStore(state => state.linkedPromptId);
  const isExtractingAeo = useGapAnalysisStore(state => state.isExtractingAeo);
  const gapDraftHistoryId = useGapAnalysisStore(state => state.gapDraftHistoryId);
  const isSavingGapDraft = useGapAnalysisStore(state => state.isSavingGapDraft);
  const gapDraftSaveStatus = useGapAnalysisStore(state => state.gapDraftSaveStatus);

  const setEditorContent = useGapAnalysisStore(state => state.setEditorContent);
  const setPublishing = useGapAnalysisStore(state => state.setPublishing);
  const setPublishError = useGapAnalysisStore(state => state.setPublishError);
  const hydrateFromParams = useGapAnalysisStore(state => state.hydrateFromParams);
  const hydrateFromVisibilityGap = useGapAnalysisStore(state => state.hydrateFromVisibilityGap);
  const mergeAeoExtract = useGapAnalysisStore(state => state.mergeAeoExtract);
  const setExtractingAeo = useGapAnalysisStore(state => state.setExtractingAeo);
  const setAutoGenerating = useGapAnalysisStore(state => state.setAutoGenerating);
  const hydrateFromAutoGenerate = useGapAnalysisStore(state => state.hydrateFromAutoGenerate);
  const setGapDraftHistoryId = useGapAnalysisStore(state => state.setGapDraftHistoryId);
  const setSavingGapDraft = useGapAnalysisStore(state => state.setSavingGapDraft);
  const setGapDraftSaveStatus = useGapAnalysisStore(state => state.setGapDraftSaveStatus);
  const reset = useGapAnalysisStore(state => state.reset);

  const {
    data: workspaceDomain,
    refetch: refetchDomain,
    isFetching: isDomainFetching,
  } = useWorkspaceDomainPreview();

  useEffect(() => {
    const clustersParam = searchParams.get('clusters')?.trim();
    const clusters = clustersParam ? clustersParam.split(',').filter(Boolean) : [];
    const sourceRouteParam = searchParams.get('sourceRoute');
    const titleParam =
      searchParams.get('prompt')?.trim() ??
      searchParams.get('title')?.trim() ??
      visibilityPrefillRef.current?.prompt;
    const clusterParam =
      searchParams.get('promptCluster')?.trim() ??
      visibilityPrefillRef.current?.promptCluster;

    if (sourceRouteParam === 'ai-visibility') {
      hydrateFromParams({
        clusters: clusterParam ? [clusterParam, ...clusters.filter(c => c !== clusterParam)] : clusters,
        sourceRoute: sourceRouteParam,
        title: titleParam,
      });
      return;
    }

    if (!resolvedPromptId && (clusters.length > 0 || sourceRouteParam === 'ai-visibility')) {
      hydrateFromParams({
        clusters,
        sourceRoute: sourceRouteParam,
        title: titleParam,
      });
    }
  }, [searchParams, hydrateFromParams, resolvedPromptId]);

  useEffect(() => {
    if (!gapData?.promptId) {
      return;
    }

    if (lastHydratedPromptIdRef.current === gapData.promptId) {
      return;
    }

    if (autoGenerateSucceededRef.current) {
      lastHydratedPromptIdRef.current = gapData.promptId;
      return;
    }

    lastHydratedPromptIdRef.current = gapData.promptId;
    hydrateFromVisibilityGap(gapData);
    if (!autoGenerate) {
      toast.message('Gap draft hydrated from Visibility Matrix', {
        description: gapData.prompt,
      });
    }
  }, [autoGenerate, gapData, hydrateFromVisibilityGap]);

  useEffect(() => {
    if (!autoGenerate || !resolvedPromptId || !effectiveProjectId || autoGenerateStartedRef.current) {
      return;
    }

    autoGenerateStartedRef.current = true;
    setAutoGenerating(true);

    const promptText =
      searchParams.get('prompt')?.trim() ||
      visibilityPrefillRef.current?.prompt ||
      gapData?.prompt ||
      '';

    const missingEntities = gapData?.targetEntities?.filter(Boolean) ?? [];

    void (async () => {
      try {
        const response = await fetch('/api/article-studio/auto-generate', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            promptId: resolvedPromptId,
            projectId: effectiveProjectId,
            promptText: promptText || undefined,
            missingEntities: missingEntities.length > 0 ? missingEntities : undefined,
          }),
        });

        const payload = (await response.json()) as {
          result?: AutoGenerateGapArticle;
          creditsDeducted?: number;
          error?: string;
        };

        if (!response.ok) {
          throw new Error(payload.error ?? 'Gap article generation failed');
        }

        if (!payload.result) {
          throw new Error('Gap article generation returned invalid data');
        }

        hydrateFromAutoGenerate({
          promptId: resolvedPromptId,
          result: payload.result,
        });
        autoGenerateSucceededRef.current = true;
        setAutoGenerateDone(true);
        setLeftTab('draft');
        toast.success(
          payload.creditsDeducted
            ? `AEO draft generated (${payload.creditsDeducted} credits used). Edit before publishing.`
            : 'AEO draft generated. Edit before publishing.'
        );
      } catch (error) {
        setAutoGenerating(false);
        setAutoGenerateDone(true);
        toast.error(
          error instanceof Error ? error.message : 'Gap article generation failed',
          {
            description: 'Matrix baseline data is still loaded — edit manually or retry.',
          }
        );
      }
    })();
  }, [
    autoGenerate,
    resolvedPromptId,
    effectiveProjectId,
    searchParams,
    gapData,
    setAutoGenerating,
    hydrateFromAutoGenerate,
  ]);

  useEffect(() => {
    if (isGapError && gapError instanceof Error) {
      toast.error(gapError.message);
    }
  }, [isGapError, gapError]);

  const liveManifest = useMemo(
    () =>
      buildLiveManifestPreview({
        metadata,
        editorContent,
        website: gapData?.brandWebsite || workspaceDomain?.website,
        brandName: gapData?.trackedBrandName || workspaceDomain?.brandName,
      }),
    [metadata, editorContent, workspaceDomain, gapData]
  );

  const mergedManifest = useMemo(() => {
    if (workspaceDomain?.manifest) {
      return {
        persistedDomainProfile: workspaceDomain.manifest,
        liveDraftProjection: liveManifest,
        manifestVersion: workspaceDomain.manifestVersion,
        linkedPromptId,
      };
    }
    return { ...liveManifest, linkedPromptId };
  }, [liveManifest, workspaceDomain, linkedPromptId]);

  async function handleSaveGapDraft() {
    if (!activeProjectId?.trim()) {
      toast.error('Select a project before saving.');
      return;
    }

    if (!metadata.title.trim()) {
      toast.error('Article title is required before saving.');
      return;
    }

    setSavingGapDraft(true);
    setGapDraftSaveStatus('saving');

    try {
      const response = await fetch('/api/article-studio/gap-draft', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          workspaceId: activeProjectId,
          projectId: activeProjectId,
          draftId: gapDraftHistoryId,
          content: editorContent,
          metadata,
          linkedPromptId,
        }),
      });

      const payload = (await response.json()) as {
        draftId?: string;
        error?: string;
      };

      if (!response.ok) {
        throw new Error(payload.error ?? 'Failed to save draft');
      }

      if (payload.draftId) {
        setGapDraftHistoryId(payload.draftId);
      }

      setGapDraftSaveStatus('saved');
      toast.success('Gap analysis draft saved to history.');
      onDraftSaved?.();
    } catch (error) {
      setGapDraftSaveStatus('error');
      toast.error(error instanceof Error ? error.message : 'Failed to save draft');
    } finally {
      setSavingGapDraft(false);
    }
  }

  async function handleAutoExtractAeo() {
    if (!editorContent.trim() || editorContent.trim().length < 80) {
      toast.error('Add at least a few paragraphs of draft content before extracting metadata.');
      return;
    }

    setExtractingAeo(true);

    try {
      const response = await fetch('/api/article-studio/extract-aeo-metadata', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          content: editorContent,
          keywordTargets: metadata.keywordTargets,
          cluster: metadata.cluster,
        }),
      });

      const payload = (await response.json()) as {
        result?: {
          metaDescription: string;
          seoTitle: string;
          faqSchemas: Array<{ question: string; answer: string }>;
          authoritativeUrls: string[];
        };
        creditsDeducted?: number;
        error?: string;
      };

      if (!response.ok) {
        throw new Error(payload.error ?? 'Metadata extraction failed');
      }

      if (!payload.result) {
        throw new Error('Metadata extraction returned invalid data');
      }

      mergeAeoExtract(payload.result);
      setLeftTab('metadata');
      toast.success(
        payload.creditsDeducted
          ? `AEO metadata generated (${payload.creditsDeducted} credit used).`
          : 'AEO metadata generated.'
      );
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Metadata extraction failed');
    } finally {
      setExtractingAeo(false);
    }
  }

  async function handlePublish() {
    if (!activeProjectId?.trim()) {
      toast.error('Select a project before publishing.');
      return;
    }

    if (!editorContent.trim()) {
      toast.error('Add article content before publishing.');
      return;
    }

    if (!metadata.title.trim()) {
      toast.error('Article title is required in metadata.');
      return;
    }

    setPublishing(true);
    setPublishError(null);

    try {
      const response = await fetch('/api/article-studio/publish', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          projectId: activeProjectId,
          content: editorContent,
          metadata,
          briefId: briefId ?? undefined,
          articleId: articleId ?? undefined,
        }),
      });

      const payload = (await response.json()) as {
        slug?: string;
        articleUrl?: string;
        error?: string;
      };

      if (!response.ok) {
        throw new Error(payload.error ?? 'Publish failed');
      }

      toast.success('Article published with JSON-LD schema injection.', {
        action: payload.articleUrl
          ? {
              label: 'View',
              onClick: () => router.push(payload.articleUrl!),
            }
          : undefined,
      });

      void refetchDomain();
      onPublished?.({
        slug: payload.slug ?? '',
        articleUrl: payload.articleUrl ?? '',
      });
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Publish failed';
      setPublishError(message);
      toast.error(message);
    } finally {
      setPublishing(false);
    }
  }

  if (autoGenerate && !autoGenerateDone) {
    return <GapAnalysisAutoGenerateSkeleton />;
  }

  return (
    <div className="flex h-full min-h-0 flex-col">
      <div className="shrink-0 border-b border-border bg-card px-4 py-4 sm:px-6">
        <div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between">
          <div>
            <p className="text-xs font-semibold uppercase tracking-wide text-emerald-600 dark:text-emerald-400">
              Gap Analysis & Drafting
            </p>
            <h2 className="mt-1 text-xl font-semibold text-foreground">
              {metadata.title || 'Untitled Gap Article'}
            </h2>
            <p className="mt-1 text-sm text-muted-foreground">
              {isGapLoading && resolvedPromptId
                ? 'Loading visibility gap from matrix…'
                : sourceRoute === 'ai-visibility'
                  ? `AI Visibility gap-fill${linkedPromptId ? ` · ${linkedPromptId}` : ''}${sourceClusters.length ? ` · ${sourceClusters.join(', ')}` : ''}`
                  : 'Structured metadata lives in Zustand — never parsed from HTML.'}
            </p>
          </div>

          <div className="flex flex-wrap items-center gap-2">
            {gapDraftSaveStatus !== 'idle' ? (
              <span
                className={cn(
                  'text-xs font-medium',
                  gapDraftSaveStatus === 'unsaved'
                    ? 'text-amber-600 dark:text-amber-400'
                    : gapDraftSaveStatus === 'saving'
                      ? 'text-muted-foreground'
                      : gapDraftSaveStatus === 'saved'
                        ? 'text-emerald-600 dark:text-emerald-400'
                        : 'text-red-600 dark:text-red-400'
                )}
              >
                {gapDraftSaveStatus === 'unsaved'
                  ? 'Unsaved changes'
                  : gapDraftSaveStatus === 'saving'
                    ? 'Saving…'
                    : gapDraftSaveStatus === 'saved'
                      ? 'Saved to history'
                      : 'Save failed'}
              </span>
            ) : null}
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={() => void handleSaveGapDraft()}
              disabled={
                isSavingGapDraft ||
                isPublishing ||
                gapDraftSaveStatus === 'saving'
              }
            >
              {isSavingGapDraft ? (
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              ) : (
                <Save className="mr-2 h-4 w-4" />
              )}
              Save Draft
            </Button>
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={() =>
                reset({
                  sourceClusters,
                  sourceRoute,
                  cluster: metadata.cluster,
                  geo: metadata.geo,
                  keywordTargets: metadata.keywordTargets,
                })
              }
            >
              Reset Draft
            </Button>
            <Button
              type="button"
              variant="outline"
              size="sm"
              disabled={isExtractingAeo || editorContent.trim().length < 80}
              onClick={() => void handleAutoExtractAeo()}
            >
              {isExtractingAeo ? (
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              ) : (
                <Sparkles className="mr-2 h-4 w-4" />
              )}
              Auto-Generate AEO Metadata ({AEO_EXTRACT_CREDIT_COST} credit)
            </Button>
            <Button
              type="button"
              size="sm"
              className="bg-emerald-600 hover:bg-emerald-500"
              onClick={() => void handlePublish()}
              disabled={isPublishing}
            >
              {isPublishing ? (
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              ) : (
                <Upload className="mr-2 h-4 w-4" />
              )}
              Publish & Update Domain Profile
            </Button>
          </div>
        </div>

        {publishError ? (
          <p className="mt-2 text-xs text-red-600 dark:text-red-400">{publishError}</p>
        ) : null}
      </div>

      <div className="hidden min-h-0 flex-1 md:flex">
        <ResizablePanelGroup direction="horizontal" className="h-full min-h-0">
          <ResizablePanel defaultSize={55} minSize={35} className="min-h-0">
            <div className="flex h-full min-h-0 flex-col border-r border-border">
              <Tabs
                value={leftTab}
                onValueChange={value => setLeftTab(value as typeof leftTab)}
                className="flex h-full min-h-0 flex-col"
              >
                <TabsList className="mx-4 mt-3 h-8 w-fit">
                  <TabsTrigger value="draft" className="text-xs">
                    Content
                  </TabsTrigger>
                  <TabsTrigger value="metadata" className="text-xs">
                    Metadata & AEO
                  </TabsTrigger>
                </TabsList>
                <TabsContent value="draft" className="mt-0 min-h-0 flex-1 data-[state=inactive]:hidden">
                  <GapAnalysisRichTextEditor
                    value={editorContent}
                    onChange={setEditorContent}
                    className="h-full"
                  />
                </TabsContent>
                <TabsContent
                  value="metadata"
                  className="mt-0 min-h-0 flex-1 overflow-hidden data-[state=inactive]:hidden"
                >
                  <ScrollArea className="h-full">
                    <GapAnalysisMetadataPanel className="p-4" />
                  </ScrollArea>
                </TabsContent>
              </Tabs>
            </div>
          </ResizablePanel>

          <ResizableHandle withHandle />

          <ResizablePanel defaultSize={45} minSize={30} className="min-h-0">
            <LiveManifestPreview
              manifest={mergedManifest}
              onRefresh={() => void refetchDomain()}
              isRefreshing={isDomainFetching}
              hasPendingDraft={workspaceDomain?.hasPendingDraft}
              draftVersion={workspaceDomain?.draftVersion}
              publishedVersion={workspaceDomain?.publishedVersion}
              className="h-full bg-zinc-950/5 dark:bg-zinc-900/40"
            />
          </ResizablePanel>
        </ResizablePanelGroup>
      </div>

      <div className="flex min-h-0 flex-1 flex-col md:hidden">
        <Tabs defaultValue="draft" className="flex min-h-0 flex-1 flex-col">
          <TabsList className="mx-4 mt-3 h-8 w-fit">
            <TabsTrigger value="draft" className="text-xs">
              Content
            </TabsTrigger>
            <TabsTrigger value="metadata" className="text-xs">
              Metadata
            </TabsTrigger>
            <TabsTrigger value="manifest" className="text-xs">
              Manifest
            </TabsTrigger>
          </TabsList>
          <TabsContent value="draft" className="min-h-[360px] flex-1 data-[state=inactive]:hidden">
            <GapAnalysisRichTextEditor value={editorContent} onChange={setEditorContent} />
          </TabsContent>
          <TabsContent value="metadata" className="min-h-[360px] flex-1 data-[state=inactive]:hidden">
            <ScrollArea className="h-[360px]">
              <GapAnalysisMetadataPanel className="p-4" />
            </ScrollArea>
          </TabsContent>
          <TabsContent value="manifest" className="min-h-[360px] flex-1 data-[state=inactive]:hidden">
            <LiveManifestPreview
              manifest={mergedManifest}
              onRefresh={() => void refetchDomain()}
              isRefreshing={isDomainFetching}
              hasPendingDraft={workspaceDomain?.hasPendingDraft}
              draftVersion={workspaceDomain?.draftVersion}
              publishedVersion={workspaceDomain?.publishedVersion}
              className="h-[360px]"
            />
          </TabsContent>
        </Tabs>
      </div>

      {effectiveProjectId ? (
        <ManifestHostingFooter
          projectId={effectiveProjectId}
          website={workspaceDomain?.website}
        />
      ) : (
        <div className="shrink-0 border-t border-border bg-muted/30 px-4 py-2 text-[11px] text-muted-foreground">
          Select a project to preview manifest hosting URLs.
        </div>
      )}
    </div>
  );
}
