
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // prisma generate does not connect; placeholder allows Docker/Coolify builds before runtime env exists.
    url:
      process.env.DATABASE_URL ??
      "postgresql://build:build@127.0.0.1:5432/build?schema=public",
  },
});
