import type { RelatedKeyword } from '@/lib/semantic-metrics';

const EMPTY_RESEARCH_FIELDS: Pick<
  RelatedKeyword,
  'monthlySearches' | 'serpFeatures' | 'yoyChange'
> = {
  monthlySearches: [],
  serpFeatures: { localPack: false, featuredSnippet: false },
  yoyChange: null,
};

export const RELATED_KEYWORDS_MOCK_DATA: RelatedKeyword[] = [
  {
    expression: 'affiliate marketing programs amazon',
    frequency: 0,
    searchVolume: 135000,
    concurrence: 4,
    cpc: 1.77,
    difficulty: 67,
    intention: 'commercial',
    interestScore: 100,
    ...EMPTY_RESEARCH_FIELDS,
  },
  {
    expression: 'affiliate marketing programs',
    frequency: 6,
    searchVolume: 33100,
    concurrence: 51,
    cpc: 2.25,
    difficulty: 72,
    intention: 'navigational',
    interestScore: 40,
    ...EMPTY_RESEARCH_FIELDS,
  },
  {
    expression: 'best marketing affiliate programs',
    frequency: 0,
    searchVolume: 12100,
    concurrence: 40,
    cpc: 2.54,
    difficulty: 72,
    intention: 'commercial',
    interestScore: 19,
    ...EMPTY_RESEARCH_FIELDS,
  },
  {
    expression: 'travel affiliate marketing programs',
    frequency: 0,
    searchVolume: 3600,
    concurrence: 28,
    cpc: 2.83,
    difficulty: 47,
    intention: 'commercial',
    interestScore: 14,
    ...EMPTY_RESEARCH_FIELDS,
  },
  {
    expression: 'fashion affiliate marketing programs',
    frequency: 0,
    searchVolume: 1600,
    concurrence: 14,
    cpc: 2.23,
    difficulty: 32,
    intention: 'commercial',
    interestScore: 12,
    ...EMPTY_RESEARCH_FIELDS,
  },
  {
    expression: 'affiliate marketing programs for beginners',
    frequency: 1,
    searchVolume: 2900,
    concurrence: 22,
    cpc: 1.95,
    difficulty: 54,
    intention: 'informational',
    interestScore: 11,
    ...EMPTY_RESEARCH_FIELDS,
  },
  {
    expression: 'high paying affiliate marketing programs',
    frequency: 0,
    searchVolume: 4400,
    concurrence: 35,
    cpc: 3.12,
    difficulty: 61,
    intention: 'commercial',
    interestScore: 10,
    ...EMPTY_RESEARCH_FIELDS,
  },
  {
    expression: 'saas affiliate marketing programs',
    frequency: 0,
    searchVolume: 2100,
    concurrence: 18,
    cpc: 4.05,
    difficulty: 58,
    intention: 'transactional',
    interestScore: 9,
    ...EMPTY_RESEARCH_FIELDS,
  },
  {
    expression: 'affiliate marketing programs list',
    frequency: 2,
    searchVolume: 5200,
    concurrence: 31,
    cpc: 1.68,
    difficulty: 49,
    intention: 'informational',
    interestScore: 8,
    ...EMPTY_RESEARCH_FIELDS,
  },
  {
    expression: 'crypto affiliate marketing programs',
    frequency: 0,
    searchVolume: 980,
    concurrence: 11,
    cpc: 3.44,
    difficulty: 44,
    intention: 'commercial',
    interestScore: 7,
    ...EMPTY_RESEARCH_FIELDS,
  },
];
