'use client';

import { useSearchParams } from 'next/navigation';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { createHubSpokeBrief, createHubSpokeBriefs, createSiloBuilderBrief, createSiloBuilderBriefs, deleteContentBrief } from '@/app/actions/content-pipeline';
import { format } from 'date-fns';
import ReactMarkdown from 'react-markdown';
import { toast } from '@/components/ui/sonner';
import { useProject } from '@/components/projects/ProjectProvider';
import { useDebounce } from '@/hooks/useDebounce';
import {
  fetchLatestToolHistoryByIdentifier,
  fetchToolHistoryEntry,
  saveToolHistoryEntry,
} from '@/lib/tool-history/client';
import {
  buildBriefLinkedHistoryPayload,
  buildStandaloneHistoryPayload,
  parseArticleStudioHistoryPayload,
  type ArticleStudioMetadataFields,
} from '@/lib/tool-history/article-studio-persistence';
import { useToolHistory } from '@/hooks/useToolHistory';
import CreateArticleDialog, { type QuickGenerateResult } from './CreateArticleDialog';
import DraftHistoryListItem from './DraftHistoryListItem';
import SavedBriefListItem from './SavedBriefListItem';
import {
  Copy,
  ChevronDown,
  Download,
  Eye,
  FileText,
  FolderOpen,
  Loader2,
  PenLine,
  Plus,
  RefreshCw,
  Save,
  Sparkles,
  Upload,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Sheet, SheetContent, SheetTitle } from '@/components/ui/sheet';
import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from '@/components/ui/resizable';
import {
  extractArticleMetadata,
  isMetaDescriptionAcceptable,
  resolveArticleMetadata,
} from '@/lib/article-metadata';
import { fetchOptimizedMetaDescription } from '@/lib/article-studio/optimize-meta-client';
import { fetchArticleStudioData } from '@/lib/article-studio/client-api';
import type { ArticleRecord, ContentBriefRecord } from '@/lib/content-pipeline-data';
import { cn } from '@/lib/utils';
import { consumeHubSpokeBulkImport } from '@/lib/hub-spoke-bulk-import';
import { consumeSiloBuilderBulkImport } from '@/lib/silo-builder/bulk-brief-import';
import {
  mergeSiloLinkMetadata,
  parseSiloLinkMetadata,
  type SiloLinkMetadata,
} from '@/lib/silo-builder/silo-link-metadata';
import PublishWordPressDialog from './PublishWordPressDialog';
import GapAnalysisWorkspace from '@/components/article-studio/gap-analysis/GapAnalysisWorkspace';
import QueryProvider from '@/components/providers/QueryProvider';
import { useGapAnalysisStore } from '@/lib/article-studio/gap-analysis-store';
import { parseGapAnalysisHistoryPayload } from '@/lib/tool-history/gap-analysis-persistence';

type ArticleStudioMode = 'classic' | 'gap-analysis';

function resolveStudioModeFromParams(
  params: Pick<URLSearchParams, 'get'>
): ArticleStudioMode {
  const sourceRoute = params.get('sourceRoute')?.trim();
  const promptId = params.get('prompt_id')?.trim() ?? params.get('gapId')?.trim();
  const autoGenerate = params.get('autoGenerate')?.trim();
  const clusters = params.get('clusters')?.trim();

  if (sourceRoute === 'ai-visibility' || promptId || autoGenerate === '1' || clusters) {
    return 'gap-analysis';
  }

  return 'classic';
}

type ArticleStudioClientProps = {
  initialData?: { briefs: ContentBriefRecord[]; articles: ArticleRecord[] };
};

type ArticleExportFormat = 'md' | 'txt' | 'docx';

type SaveStatus = 'idle' | 'unsaved' | 'saving' | 'saved' | 'error';

const AUTO_SAVE_DELAY_MS = 2500;

/** Survives React Strict Mode remounts to prevent duplicate Hub & Spoke auto-generation. */
const hubSpokeHydratedImportKeys = new Set<string>();
const hubSpokeAutoGeneratedBriefIds = new Set<number>();
const hubSpokeBulkImportKeys = new Set<string>();
const siloBuilderHydratedImportKeys = new Set<string>();
const siloBuilderBulkImportKeys = new Set<string>();

function buildExportFilename(source: string, extension: ArticleExportFormat): string {
  const slug =
    source
      .trim()
      .replace(/\s+/g, '-')
      .toLowerCase()
      .replace(/[^a-z0-9-]/g, '') || 'article';

  return `${slug}.${extension}`;
}

function triggerFileDownload(blob: Blob, filename: string): void {
  const downloadUrl = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = downloadUrl;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(downloadUrl);
}

function markdownToPlainText(markdown: string): string {
  return markdown
    .replace(/^#{1,6}\s+/gm, '')
    .replace(/\*\*(.+?)\*\*/g, '$1')
    .replace(/\*(.+?)\*/g, '$1')
    .replace(/!\[([^\]]*)\]\([^)]+\)/g, '$1')
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    .replace(/`([^`]+)`/g, '$1')
    .replace(/^>\s+/gm, '')
    .replace(/^[-*+]\s+/gm, '• ')
    .replace(/^\d+\.\s+/gm, '')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

type GeneratedArticleFields = {
  article: ArticleRecord;
  seoTitle: string;
  metaDescription: string;
};

function parseGeneratedArticleResponse(
  payload: unknown,
  fallbackTitle: string
): GeneratedArticleFields | null {
  try {
    if (typeof payload !== 'object' || payload === null) {
      return null;
    }

    const record = payload as Record<string, unknown>;
    const article =
      typeof record.article === 'object' && record.article !== null
        ? (record.article as ArticleRecord)
        : null;

    if (!article || typeof article.content !== 'string' || !article.content.trim()) {
      return null;
    }

    const content = article.content.trim();
    const extracted = extractArticleMetadata(content, fallbackTitle);
    const seoTitle =
      typeof record.seoTitle === 'string' && record.seoTitle.trim()
        ? record.seoTitle.trim()
        : extracted.seoTitle ?? '';
    const metaDescription =
      typeof record.metaDescription === 'string' && record.metaDescription.trim()
        ? record.metaDescription.trim()
        : extracted.metaDescription?.trim() || '';

    return {
      article: { ...article, content },
      seoTitle,
      metaDescription,
    };
  } catch {
    return null;
  }
}

function parseQuickGenerateResponsePayload(
  payload: unknown,
  fallbackTitle: string
): Pick<GeneratedArticleFields, 'seoTitle' | 'metaDescription'> & {
  title: string;
  content: string;
} | null {
  try {
    if (typeof payload !== 'object' || payload === null) {
      return null;
    }

    const record = payload as Record<string, unknown>;
    const content = typeof record.content === 'string' ? record.content.trim() : '';
    if (!content) {
      return null;
    }

    const extracted = extractArticleMetadata(content, fallbackTitle);
    const title =
      typeof record.title === 'string' && record.title.trim()
        ? record.title.trim()
        : fallbackTitle;
    const seoTitle =
      typeof record.seoTitle === 'string' && record.seoTitle.trim()
        ? record.seoTitle.trim()
        : extracted.seoTitle ?? title;
    const metaDescription =
      typeof record.metaDescription === 'string' && record.metaDescription.trim()
        ? record.metaDescription.trim()
        : extracted.metaDescription?.trim() || '';

    return { title, content, seoTitle, metaDescription };
  } catch {
    return null;
  }
}

function applyGeneratedFieldsToEditor(
  fields: Pick<GeneratedArticleFields, 'seoTitle' | 'metaDescription'> & { content: string },
  setters: {
    setDraftContent: (value: string) => void;
    setSeoTitle: (value: string) => void;
    setMetaDescription: (value: string) => void;
    setLastSavedSnapshot: (snapshot: DraftSnapshot) => void;
  }
) {
  setters.setDraftContent(fields.content);
  setters.setSeoTitle(fields.seoTitle);
  setters.setMetaDescription(fields.metaDescription);
  setters.setLastSavedSnapshot(
    createDraftSnapshot(fields.content, fields.seoTitle, fields.metaDescription)
  );
}

type WorkspaceSelection =
  | { type: 'brief'; briefId: number }
  | { type: 'standalone'; historyId: string }
  | null;

function getExportNameSource(
  editorTitle: string,
  activeArticle: ArticleRecord | null,
  selectedBrief: ContentBriefRecord | null
): string {
  return editorTitle || activeArticle?.title || selectedBrief?.targetKeyword || 'article';
}

function getLatestArticle(brief: ContentBriefRecord): ArticleRecord | null {
  return brief.articles[0] ?? null;
}

function truncateBriefSummary(content: string, maxLength = 320): string {
  const stripped = content
    .replace(/^#+\s+/gm, '')
    .replace(/\*\*/g, '')
    .replace(/\n+/g, ' ')
    .trim();
  if (stripped.length <= maxLength) {
    return stripped;
  }
  return `${stripped.slice(0, maxLength).trim()}…`;
}

type DraftSnapshot = {
  content: string;
  seoTitle: string;
  metaDescription: string;
};

function createDraftSnapshot(
  content: string,
  seoTitle: string,
  metaDescription: string
): DraftSnapshot {
  return {
    content: content.trim(),
    seoTitle: seoTitle.trim(),
    metaDescription: metaDescription.trim(),
  };
}

function draftSnapshotsEqual(a: DraftSnapshot, b: DraftSnapshot): boolean {
  return (
    a.content === b.content &&
    a.seoTitle === b.seoTitle &&
    a.metaDescription === b.metaDescription
  );
}

function resolveMetadataFields(
  content: string,
  fallbackTitle: string,
  saved?: ArticleStudioMetadataFields
): Pick<DraftSnapshot, 'seoTitle' | 'metaDescription'> {
  return resolveArticleMetadata(content, fallbackTitle, saved);
}

async function ensureGeoOptimizedMetaDescription(input: {
  targetKeyword: string;
  seoTitle: string;
  articleContent: string;
  briefId?: number;
  currentMeta?: string;
}): Promise<string> {
  const targetKeyword = input.targetKeyword.trim();
  const seoTitle = input.seoTitle.trim();
  const currentMeta = input.currentMeta?.trim() ?? '';

  if (
    currentMeta &&
    isMetaDescriptionAcceptable(currentMeta, targetKeyword)
  ) {
    return currentMeta;
  }

  try {
    const optimized = await fetchOptimizedMetaDescription({
      targetKeyword,
      seoTitle,
      articleContent: input.articleContent,
      briefId: input.briefId,
      existingMeta: currentMeta || undefined,
    });

    return optimized ?? currentMeta;
  } catch {
    return currentMeta;
  }
}

function EditableMetadataField({
  label,
  value,
  onChange,
  onCopy,
  placeholder,
  multiline = false,
}: {
  label: string;
  value: string;
  onChange: (value: string) => void;
  onCopy: () => void;
  placeholder: string;
  multiline?: boolean;
}) {
  const fieldClassName =
    'w-full rounded-md border border-transparent bg-muted/80 px-3 py-2 text-sm leading-relaxed text-foreground outline-none transition-colors placeholder:text-muted-foreground focus:border-emerald-500/40 focus:bg-card focus:ring-2 focus:ring-emerald-500/20';

  return (
    <div className="w-full max-w-full min-w-0 rounded-xl border border-border bg-card p-4 shadow-sm">
      <div className="mb-2 flex items-center justify-between gap-2">
        <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{label}</p>
        <Button
          type="button"
          variant="ghost"
          size="sm"
          className="h-7 gap-1.5 px-2 text-xs text-emerald-600 hover:bg-emerald-50 hover:text-emerald-700 dark:text-emerald-300 dark:hover:bg-emerald-950/40 dark:hover:text-emerald-200"
          onClick={onCopy}
          disabled={!value.trim()}
        >
          <Copy className="h-3.5 w-3.5" />
          Copy
        </Button>
      </div>
      {multiline ? (
        <textarea
          value={value}
          onChange={event => onChange(event.target.value)}
          placeholder={placeholder}
          rows={3}
          className={cn(fieldClassName, 'min-h-[88px] resize-y')}
        />
      ) : (
        <input
          type="text"
          value={value}
          onChange={event => onChange(event.target.value)}
          placeholder={placeholder}
          className={fieldClassName}
        />
      )}
    </div>
  );
}

function SaveStatusIndicator({
  status,
}: {
  status: SaveStatus;
}) {
  if (status === 'idle') {
    return null;
  }

  const label =
    status === 'unsaved'
      ? 'Unsaved changes'
      : status === 'saving'
        ? 'Saving…'
        : status === 'saved'
          ? 'Saved to history'
          : 'Save failed';

  const className =
    status === 'unsaved'
      ? 'text-amber-600'
      : status === 'saving'
        ? 'text-muted-foreground'
        : status === 'saved'
          ? 'text-emerald-600'
          : 'text-red-600';

  return (
    <span className={cn('flex items-center gap-1.5 text-xs font-medium', className)}>
      {status === 'saving' ? <Loader2 className="h-3 w-3 animate-spin" /> : null}
      {label}
    </span>
  );
}

function GenerationSkeleton() {
  return (
    <div className="space-y-6">
      <div className="grid gap-4 sm:grid-cols-2">
        <Skeleton className="h-24 rounded-xl" />
        <Skeleton className="h-24 rounded-xl" />
      </div>
      <Skeleton className="h-10 w-64 rounded-lg" />
      <div className="grid gap-4 lg:grid-cols-2">
        <Skeleton className="h-[420px] rounded-xl" />
        <Skeleton className="h-[420px] rounded-xl" />
      </div>
    </div>
  );
}

export default function ArticleStudioClient({ initialData }: ArticleStudioClientProps = {}) {
  const searchParams = useSearchParams();
  const { activeProjectId, isLoading: isProjectLoading } = useProject();
  const projectId = activeProjectId;
  const didHydrateFromParams = useRef(false);
  const pendingAutoGenerateBriefIdRef = useRef<number | null>(null);

  const [briefs, setBriefs] = useState<ContentBriefRecord[]>(initialData?.briefs ?? []);
  const [selection, setSelection] = useState<WorkspaceSelection>(null);
  const [activeArticle, setActiveArticle] = useState<ArticleRecord | null>(null);
  const [draftContent, setDraftContent] = useState('');
  const [editorTitle, setEditorTitle] = useState('');
  const [seoTitle, setSeoTitle] = useState('');
  const [metaDescription, setMetaDescription] = useState('');
  const [standaloneSource, setStandaloneSource] = useState<'blank' | 'quick-ai'>('blank');
  const [isCreateDialogOpen, setIsCreateDialogOpen] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [awaitingAutoGenerate, setAwaitingAutoGenerate] = useState(false);
  const [isQuickGenerating, setIsQuickGenerating] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [isExporting, setIsExporting] = useState(false);
  const [isWordPressDialogOpen, setIsWordPressDialogOpen] = useState(false);
  const [deletingDraftId, setDeletingDraftId] = useState<string | null>(null);
  const [deletingBriefId, setDeletingBriefId] = useState<number | null>(null);
  const [workspaceTab, setWorkspaceTab] = useState<'split' | 'edit' | 'preview'>('split');
  const [historyId, setHistoryId] = useState<string | null>(null);
  const [siloLink, setSiloLink] = useState<SiloLinkMetadata | null>(null);
  const [saveStatus, setSaveStatus] = useState<SaveStatus>('idle');
  const [mobileSidebarOpen, setMobileSidebarOpen] = useState(false);
  const [studioMode, setStudioMode] = useState<ArticleStudioMode>(() =>
    resolveStudioModeFromParams(searchParams)
  );

  const lastSavedSnapshotRef = useRef<DraftSnapshot>(
    createDraftSnapshot('', '', '')
  );
  const debouncedDraftContent = useDebounce(draftContent, AUTO_SAVE_DELAY_MS);
  const debouncedSeoTitle = useDebounce(seoTitle, AUTO_SAVE_DELAY_MS);
  const debouncedMetaDescription = useDebounce(metaDescription, AUTO_SAVE_DELAY_MS);

  const isSavingRef = useRef(false);
  const suppressAutoSaveRef = useRef(false);
  const generationInFlightRef = useRef(false);
  const siloLinkRef = useRef<SiloLinkMetadata | null>(null);

  const applySiloLink = useCallback((metadata: SiloLinkMetadata | null) => {
    siloLinkRef.current = metadata;
    setSiloLink(metadata);
  }, []);

  const resolveActiveHistoryId = useCallback((): string | null => {
    if (selection?.type === 'standalone') {
      return selection.historyId;
    }
    return historyId;
  }, [historyId, selection]);

  const { entries: historyEntries, refresh: refreshHistory, remove: removeHistoryEntry } =
    useToolHistory('article-studio', {
      limit: 100,
      workspaceId: activeProjectId,
    });

  useEffect(() => {
    setSelection(null);
    setActiveArticle(null);
    setDraftContent('');
    setEditorTitle('');
    setSeoTitle('');
    setMetaDescription('');
    setHistoryId(null);
    setSaveStatus('idle');
    setStandaloneSource('blank');
    setWorkspaceTab('split');
    setBriefs([]);
    lastSavedSnapshotRef.current = createDraftSnapshot('', '', '');

    if (!(activeProjectId ?? "").trim()) {
      return;
    }

    void fetchArticleStudioData(activeProjectId)
      .then(data => setBriefs(data.briefs))
      .catch(() => setBriefs([]));
  }, [activeProjectId]);

  useEffect(() => {
    const sourceRoute = searchParams.get('sourceRoute')?.trim();
    const clustersParam = searchParams.get('clusters')?.trim();
    const promptIdParam =
      searchParams.get('prompt_id')?.trim() ?? searchParams.get('gapId')?.trim();
    const autoGenerateParam = searchParams.get('autoGenerate')?.trim();
    if (
      sourceRoute === 'ai-visibility' ||
      clustersParam ||
      promptIdParam ||
      autoGenerateParam === '1'
    ) {
      setStudioMode('gap-analysis');
    }
  }, [searchParams]);

  const gapWorkspaceKey = useMemo(() => {
    const promptId =
      searchParams.get('prompt_id')?.trim() ??
      searchParams.get('gapId')?.trim() ??
      '';
    const autoGenerate = searchParams.get('autoGenerate')?.trim() ?? '';
    return `${promptId}:${autoGenerate}`;
  }, [searchParams]);

  const standaloneDrafts = historyEntries;

  const selectedBriefId = selection?.type === 'brief' ? selection.briefId : null;

  const selectedBrief = useMemo(
    () => briefs.find(brief => brief.id === selectedBriefId) ?? null,
    [briefs, selectedBriefId]
  );

  const isStandaloneEditor = selection?.type === 'standalone';
  const isEditorActive =
    isStandaloneEditor || (selection?.type === 'brief' && activeArticle !== null);

  const isDirty = !draftSnapshotsEqual(
    createDraftSnapshot(draftContent, seoTitle, metaDescription),
    lastSavedSnapshotRef.current
  );

  const applyMetadataState = useCallback(
    (
      content: string,
      fallbackTitle: string,
      saved?: ArticleStudioMetadataFields,
      snapshotContent?: string
    ) => {
      const resolved = resolveMetadataFields(content, fallbackTitle, saved);
      setSeoTitle(resolved.seoTitle);
      setMetaDescription(resolved.metaDescription);
      lastSavedSnapshotRef.current = createDraftSnapshot(
        snapshotContent ?? content,
        resolved.seoTitle,
        resolved.metaDescription
      );
    },
    []
  );

  const loadHistoryIdForBrief = useCallback(async (brief: ContentBriefRecord) => {
    try {
      const entry = await fetchLatestToolHistoryByIdentifier(
        'article-studio',
        brief.targetKeyword,
        projectId
      );
      const id = entry?.id ?? null;
      setHistoryId(id);
      return id;
    } catch {
      setHistoryId(null);
      return null;
    }
  }, [projectId]);

  const syncBriefArticleState = useCallback(
    (briefId: number, article: ArticleRecord) => {
      setBriefs(prev =>
        prev.map(brief => {
          if (brief.id !== briefId) {
            return brief;
          }

          return {
            ...brief,
            articles: [article, ...brief.articles.filter(item => item.id !== article.id)],
          };
        })
      );
    },
    []
  );

  const saveDraft = useCallback(
    async (options?: {
      silent?: boolean;
      contentOverride?: string;
      seoTitleOverride?: string;
      metaDescriptionOverride?: string;
      draftIdOverride?: string | null;
      articleIdOverride?: number;
    }) => {
      const contentToSave = options?.contentOverride ?? draftContent;
      const seoTitleToSave = options?.seoTitleOverride ?? seoTitle;
      const metaDescriptionToSave = options?.metaDescriptionOverride ?? metaDescription;
      const nextSnapshot = createDraftSnapshot(
        contentToSave,
        seoTitleToSave,
        metaDescriptionToSave
      );

      if (draftSnapshotsEqual(nextSnapshot, lastSavedSnapshotRef.current)) {
        if (saveStatus === 'unsaved') {
          setSaveStatus('saved');
        }
        return;
      }

      if (isSavingRef.current) {
        return;
      }

      if (!projectId.trim()) {
        if (!options?.silent) {
          toast.error('Select a project before saving a draft.');
        }
        return;
      }

      const activeHistoryId = resolveActiveHistoryId();

      if (selection?.type === 'standalone') {
        if (!activeHistoryId) {
          return;
        }

        isSavingRef.current = true;
        setIsSaving(true);
        setSaveStatus('saving');

        try {
          const resultData = {
            ...buildStandaloneHistoryPayload({
              title: editorTitle,
              content: contentToSave,
              source: standaloneSource,
              seoTitle: seoTitleToSave,
              metaDescription: metaDescriptionToSave,
            }),
            projectId,
          };

          const historyEntry = await saveToolHistoryEntry('article-studio', {
            id: activeHistoryId,
            identifier: editorTitle,
            resultData,
            workspaceId: projectId,
          });

          setHistoryId(historyEntry.id);
          setEditorTitle(resultData.draftTitle);
          lastSavedSnapshotRef.current = nextSnapshot;
          setSaveStatus('saved');
          await refreshHistory();

          if (!options?.silent) {
            toast.success('Draft saved to history.');
          }
        } catch (saveError) {
          setSaveStatus('error');
          if (!options?.silent) {
            toast.error(saveError instanceof Error ? saveError.message : 'Failed to save draft.');
          }
        } finally {
          isSavingRef.current = false;
          setIsSaving(false);
        }
        return;
      }

      if (!selectedBrief || !activeArticle) {
        return;
      }

      const articleIdToSave = options?.articleIdOverride ?? activeArticle.id;
      let draftIdToSave = options?.draftIdOverride ?? resolveActiveHistoryId();

      isSavingRef.current = true;
      setIsSaving(true);
      setSaveStatus('saving');

      try {
        if (!draftIdToSave) {
          try {
            const existingEntry = await fetchLatestToolHistoryByIdentifier(
              'article-studio',
              selectedBrief.targetKeyword,
              projectId
            );
            draftIdToSave = existingEntry?.id ?? null;
          } catch {
            draftIdToSave = null;
          }
        }

        const activeSiloLink = siloLinkRef.current;
        const briefResultData = {
          ...buildBriefLinkedHistoryPayload(
            selectedBrief,
            { ...activeArticle, id: articleIdToSave },
            contentToSave,
            {
              seoTitle: seoTitleToSave,
              metaDescription: metaDescriptionToSave,
            }
          ),
          projectId,
          state:
            contentToSave.trim().length > 80
              ? 'generated'
              : activeSiloLink?.state ?? 'brief',
        };

        const resultData = activeSiloLink
          ? mergeSiloLinkMetadata(briefResultData, {
              ...activeSiloLink,
              articleStudioHistoryId:
                draftIdToSave ?? activeSiloLink.articleStudioHistoryId,
            })
          : briefResultData;

        const response = await fetch('/api/article-studio/draft', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            draftId: draftIdToSave,
            articleId: articleIdToSave,
            content: contentToSave,
            title: editorTitle || activeArticle.title,
            identifier: selectedBrief.targetKeyword,
            resultData,
            workspaceId: projectId,
          }),
        });

        const payload = await response.json().catch(() => ({}));

        if (!response.ok) {
          const message =
            typeof payload === 'object' && payload !== null && 'error' in payload
              ? String(payload.error)
              : 'Failed to save draft.';
          throw new Error(message);
        }

        const article =
          typeof payload === 'object' && payload !== null && 'article' in payload
            ? (payload.article as ArticleRecord)
            : null;
        const savedDraftId =
          typeof payload === 'object' && payload !== null && 'draftId' in payload
            ? String(payload.draftId)
            : draftIdToSave;

        if (!article) {
          throw new Error('Save returned invalid data.');
        }

        setHistoryId(savedDraftId);
        setActiveArticle(article);
        setEditorTitle(article.title);
        setDraftContent(article.content);
        lastSavedSnapshotRef.current = nextSnapshot;
        syncBriefArticleState(selectedBrief.id, article);
        if (activeSiloLink?.siloNodeId) {
          applySiloLink({
            ...activeSiloLink,
            articleStudioHistoryId: savedDraftId ?? activeSiloLink.articleStudioHistoryId,
            state: contentToSave.trim().length > 80 ? 'generated' : activeSiloLink.state,
          });
        }
        setSaveStatus('saved');
        await refreshHistory();

        if (!options?.silent) {
          toast.success('Draft saved to history.');
        }
      } catch (saveError) {
        setSaveStatus('error');
        if (!options?.silent) {
          toast.error(saveError instanceof Error ? saveError.message : 'Failed to save draft.');
        }
      } finally {
        isSavingRef.current = false;
        setIsSaving(false);
      }
    },
    [
      activeArticle,
      projectId,
      activeProjectId,
      draftContent,
      editorTitle,
      historyId,
      metaDescription,
      refreshHistory,
      resolveActiveHistoryId,
      saveStatus,
      selectedBrief,
      selection,
      seoTitle,
      standaloneSource,
      syncBriefArticleState,
      applySiloLink,
    ]
  );

  async function activateStandaloneDraft(historyIdToLoad: string) {
    suppressAutoSaveRef.current = true;

    try {
      const entry = await fetchToolHistoryEntry('article-studio', historyIdToLoad, projectId);
      const gapPayload = parseGapAnalysisHistoryPayload(entry.resultData);

      if (gapPayload) {
        setStudioMode('gap-analysis');
        setSelection(null);
        setActiveArticle(null);
        setHistoryId(null);
        useGapAnalysisStore.getState().hydrateFromGapDraft({
          metadata: gapPayload.gapMetadata,
          editorContent: gapPayload.draftContent,
          linkedPromptId: gapPayload.linkedPromptId,
          draftHistoryId: entry.id,
        });
        setWorkspaceTab('split');
        toast.success('Gap analysis draft loaded.');
        return;
      }

      const payload = parseArticleStudioHistoryPayload(entry.resultData);

      if (!payload) {
        throw new Error('Invalid draft data.');
      }

      if (payload.source === 'brief' && payload.legacyBriefId) {
        await handleSelectBrief(payload.legacyBriefId, entry.id);
        const article = payload.activeArticle ?? null;
        if (article) {
          setActiveArticle(article);
          setDraftContent(article.content);
          setEditorTitle(article.title);
          applyMetadataState(article.content, article.title, payload, article.content);
          setSaveStatus('saved');
        }
        setHistoryId(entry.id);
        setWorkspaceTab('split');
        return;
      }

      setSelection({ type: 'standalone', historyId: entry.id });
      setActiveArticle(null);
      setHistoryId(entry.id);
      setEditorTitle(payload.draftTitle || payload.targetKeyword);
      setDraftContent(payload.draftContent ?? '');
      setStandaloneSource(payload.source === 'quick-ai' ? 'quick-ai' : 'blank');
      applyMetadataState(
        payload.draftContent ?? '',
        payload.draftTitle || payload.targetKeyword,
        payload,
        payload.draftContent ?? ''
      );
      setSaveStatus('saved');
      setWorkspaceTab('split');
    } finally {
      suppressAutoSaveRef.current = false;
    }
  }

  async function handleStartBlankDraft(title: string) {
    const resultData = {
      ...buildStandaloneHistoryPayload({
        title,
        content: '',
        source: 'blank',
      }),
      projectId,
    };

    const entry = await saveToolHistoryEntry('article-studio', {
      identifier: title,
      resultData,
      workspaceId: projectId,
    });

    setSelection({ type: 'standalone', historyId: entry.id });
    setActiveArticle(null);
    setHistoryId(entry.id);
    setEditorTitle(title);
    setDraftContent('');
    setStandaloneSource('blank');
    setSeoTitle('');
    setMetaDescription('');
    lastSavedSnapshotRef.current = createDraftSnapshot('', '', '');
    setSaveStatus('unsaved');
    setWorkspaceTab('split');
    await refreshHistory();
    toast.success('Blank draft ready. Start typing in the editor.');
  }

  async function handleQuickGenerateDraft(input: {
    title: string;
    wordCount: number;
    additionalContext?: string;
  }): Promise<QuickGenerateResult> {
    setIsQuickGenerating(true);

    try {
      const response = await fetch('/api/article-studio/quick-generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(input),
      });

      const payload = await response.json().catch(() => ({}));

      if (!response.ok) {
        const message =
          typeof payload === 'object' && payload !== null && 'error' in payload
            ? String(payload.error)
            : 'Quick AI generation failed.';
        throw new Error(message);
      }

      const parsed = parseQuickGenerateResponsePayload(payload, input.title);
      if (!parsed) {
        throw new Error('Quick AI generation returned invalid data.');
      }

      const resultData = {
        ...buildStandaloneHistoryPayload({
          title: input.title,
          content: parsed.content,
          source: 'quick-ai',
          seoTitle: parsed.seoTitle,
          metaDescription: parsed.metaDescription,
          wordCount: input.wordCount,
          additionalContext: input.additionalContext,
        }),
        projectId,
      };

      const entry = await saveToolHistoryEntry('article-studio', {
        identifier: input.title,
        resultData,
        workspaceId: projectId,
      });

      setSelection({ type: 'standalone', historyId: entry.id });
      setActiveArticle(null);
      setHistoryId(entry.id);
      setEditorTitle(parsed.title || input.title);
      applyGeneratedFieldsToEditor(parsed, {
        setDraftContent,
        setSeoTitle,
        setMetaDescription,
        setLastSavedSnapshot: snapshot => {
          lastSavedSnapshotRef.current = snapshot;
        },
      });
      setStandaloneSource('quick-ai');
      setSaveStatus('unsaved');
      setWorkspaceTab('split');
      await refreshHistory();

      void saveDraft({
        silent: true,
        contentOverride: parsed.content,
        seoTitleOverride: parsed.seoTitle,
        metaDescriptionOverride: parsed.metaDescription,
      });
      toast.success('AI draft generated and saved to history.');

      return {
        title: parsed.title,
        seoTitle: parsed.seoTitle,
        metaDescription: parsed.metaDescription,
        content: parsed.content,
        wordCount: input.wordCount,
        additionalContext: input.additionalContext,
      } satisfies QuickGenerateResult;
    } finally {
      setIsQuickGenerating(false);
    }
  }

  async function handleSelectStandaloneDraft(historyId: string) {
    try {
      await activateStandaloneDraft(historyId);
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Failed to load draft.');
    }
  }

  async function handleDeleteDraft(id: string) {
    setDeletingDraftId(id);

    try {
      await removeHistoryEntry(id);

      if (selection?.type === 'standalone' && selection.historyId === id) {
        setSelection(null);
        setActiveArticle(null);
        setDraftContent('');
        setEditorTitle('');
        setSeoTitle('');
        setMetaDescription('');
        setHistoryId(null);
        setSaveStatus('idle');
        lastSavedSnapshotRef.current = createDraftSnapshot('', '', '');
      }

      toast.success('Draft deleted.');
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Failed to delete draft.');
    } finally {
      setDeletingDraftId(null);
    }
  }

  async function handleDeleteBrief(briefId: number) {
    if (!projectId.trim()) {
      toast.error('Select a project before deleting a brief.');
      return;
    }

    setDeletingBriefId(briefId);

    try {
      await deleteContentBrief(briefId, projectId);

      setBriefs(prev => prev.filter(brief => brief.id !== briefId));
      hubSpokeAutoGeneratedBriefIds.delete(briefId);

      if (selection?.type === 'brief' && selection.briefId === briefId) {
        setSelection(null);
        setActiveArticle(null);
        setDraftContent('');
        setEditorTitle('');
        setSeoTitle('');
        setMetaDescription('');
        setHistoryId(null);
        setSaveStatus('idle');
        lastSavedSnapshotRef.current = createDraftSnapshot('', '', '');
      }

      await refreshHistory();
      toast.success('Brief deleted.');
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Failed to delete brief.');
    } finally {
      setDeletingBriefId(null);
    }
  }

  async function handleSelectBrief(briefId: number, knownHistoryId?: string) {
    const shouldManageSuppress = !suppressAutoSaveRef.current;
    if (shouldManageSuppress) {
      suppressAutoSaveRef.current = true;
    }

    try {
      setSelection({ type: 'brief', briefId });
      const brief = briefs.find(item => item.id === briefId);
      const article = brief ? getLatestArticle(brief) : null;
      setActiveArticle(article);
      setDraftContent(article?.content ?? '');
      setEditorTitle(article?.title ?? brief?.targetKeyword ?? '');
      setStandaloneSource('blank');

      let historyPayload: ArticleStudioMetadataFields | undefined;

      if (article && brief) {
        applyMetadataState(article.content, article.title || brief.targetKeyword);
        setSaveStatus('saved');
      } else {
        setSeoTitle('');
        setMetaDescription('');
        lastSavedSnapshotRef.current = createDraftSnapshot('', '', '');
        setSaveStatus('idle');
      }

      if (knownHistoryId) {
        setHistoryId(knownHistoryId);
        try {
          const entry = await fetchToolHistoryEntry('article-studio', knownHistoryId, projectId);
          const payload = parseArticleStudioHistoryPayload(entry.resultData);
          const siloMetadata = parseSiloLinkMetadata(entry.resultData);
          if (siloMetadata) {
            applySiloLink({
              ...siloMetadata,
              articleStudioHistoryId: entry.id,
            });
          }
          if (payload && article) {
            historyPayload = payload;
            applyMetadataState(
              article.content,
              article.title || brief!.targetKeyword,
              payload,
              article.content
            );
            setSaveStatus('saved');
          }
        } catch {
          // Fall back to extracted metadata from article content.
        }
      } else if (brief) {
        const linkedHistoryId = await loadHistoryIdForBrief(brief);
        setHistoryId(linkedHistoryId);
        if (linkedHistoryId) {
          try {
            const entry = await fetchToolHistoryEntry('article-studio', linkedHistoryId, projectId);
            const payload = parseArticleStudioHistoryPayload(entry.resultData);
            const siloMetadata = parseSiloLinkMetadata(entry.resultData);
            if (siloMetadata) {
              applySiloLink({
                ...siloMetadata,
                articleStudioHistoryId: entry.id,
              });
            }
            if (payload && article) {
              historyPayload = payload;
              applyMetadataState(
                article.content,
                article.title || brief.targetKeyword,
                payload,
                article.content
              );
              setSaveStatus('saved');
            }
          } catch {
            // Fall back to extracted metadata from article content.
          }
        }
      } else {
        setHistoryId(null);
      }

      if (article && brief) {
        const resolved = resolveMetadataFields(
          article.content,
          article.title || brief.targetKeyword,
          historyPayload
        );
        const optimizedMetaDescription = await ensureGeoOptimizedMetaDescription({
          targetKeyword: brief.targetKeyword,
          seoTitle: resolved.seoTitle,
          articleContent: article.content,
          briefId: brief.id,
          currentMeta: resolved.metaDescription,
        });

        setSeoTitle(resolved.seoTitle);
        setMetaDescription(optimizedMetaDescription);
        lastSavedSnapshotRef.current = createDraftSnapshot(
          article.content,
          resolved.seoTitle,
          optimizedMetaDescription
        );

        if (optimizedMetaDescription !== resolved.metaDescription) {
          setSaveStatus('unsaved');
          void saveDraft({
            silent: true,
            contentOverride: article.content,
            seoTitleOverride: resolved.seoTitle,
            metaDescriptionOverride: optimizedMetaDescription,
            articleIdOverride: article.id,
          });
        }
      }
    } finally {
      if (shouldManageSuppress) {
        suppressAutoSaveRef.current = false;
      }
    }
  }

  useEffect(() => {
    const sourceParam = searchParams.get('source')?.trim() ?? '';
    const targetKeywordParam = searchParams.get('targetKeyword')?.trim() ?? '';
    const titleParam = searchParams.get('title')?.trim() ?? '';

    if (!targetKeywordParam || isProjectLoading || !projectId.trim()) {
      return;
    }

    if (sourceParam === 'silo-builder') {
      const siloNodeId = searchParams.get('siloNodeId')?.trim() ?? '';
      const siloProjectId = searchParams.get('siloProjectId')?.trim() ?? '';
      const siloProjectTitle = searchParams.get('siloProjectTitle')?.trim() ?? 'Silo Builder';
      const intentParam = searchParams.get('intent')?.trim() ?? '';

      if (!siloNodeId || !siloProjectId) {
        return;
      }

      const importKey = `${projectId}:silo:${siloNodeId}`;
      if (siloBuilderHydratedImportKeys.has(importKey)) {
        return;
      }
      siloBuilderHydratedImportKeys.add(importKey);
      didHydrateFromParams.current = true;

      applySiloLink({
        siloNodeId,
        siloProjectId,
        siloSource: 'silo-builder',
        state: 'brief',
      });

      void (async () => {
        try {
          const brief = await createSiloBuilderBrief(
            {
              siloNodeId,
              siloProjectId,
              siloProjectTitle,
              targetKeyword: targetKeywordParam,
              title: titleParam || targetKeywordParam,
              intent: intentParam || null,
            },
            projectId
          );

          setBriefs(prev => {
            const existingIds = new Set(prev.map(item => item.id));
            return existingIds.has(brief.id) ? prev : [brief, ...prev];
          });
          setSelection({ type: 'brief', briefId: brief.id });
          setActiveArticle(null);
          setDraftContent('');
          setEditorTitle(titleParam || brief.targetKeyword);
          setSeoTitle('');
          setMetaDescription('');
          toast.success(`Brief created for "${brief.targetKeyword}".`);
        } catch (hydrateError) {
          toast.error(
            hydrateError instanceof Error
              ? hydrateError.message
              : 'Failed to create a brief from Silo Builder.'
          );
        }
      })();
      return;
    }

    const importKey = `${projectId}:${targetKeywordParam.toLowerCase()}`;
    if (hubSpokeHydratedImportKeys.has(importKey)) {
      return;
    }
    hubSpokeHydratedImportKeys.add(importKey);
    didHydrateFromParams.current = true;

    const normalizedKeyword = targetKeywordParam.toLowerCase();
    const existingBrief = briefs.find(
      brief => brief.targetKeyword.trim().toLowerCase() === normalizedKeyword
    );

    if (existingBrief) {
      const latestArticle = getLatestArticle(existingBrief);
      if (!latestArticle) {
        pendingAutoGenerateBriefIdRef.current = existingBrief.id;
        setAwaitingAutoGenerate(true);
      }
      void handleSelectBrief(existingBrief.id);
      const diagnosis = searchParams.get('diagnosis')?.trim();
      toast.success(
        diagnosis
          ? `Loaded brief for "${existingBrief.targetKeyword}" (${diagnosis}).`
          : `Loaded brief for "${existingBrief.targetKeyword}".`
      );
      return;
    }

    void (async () => {
      try {
        const brief = await createHubSpokeBrief(
          targetKeywordParam,
          titleParam || targetKeywordParam,
          projectId
        );
        setBriefs(prev => [brief, ...prev]);
        setSelection({ type: 'brief', briefId: brief.id });
        setActiveArticle(null);
        setDraftContent('');
        setEditorTitle(brief.targetKeyword);
        setSeoTitle('');
        setMetaDescription('');
        pendingAutoGenerateBriefIdRef.current = brief.id;
        setAwaitingAutoGenerate(true);
        const diagnosis = searchParams.get('diagnosis')?.trim();
        const deltaPct = searchParams.get('metricDeltaPct')?.trim();
        toast.success(
          diagnosis
            ? `Revenue Rescue brief for "${brief.targetKeyword}" (${diagnosis}${deltaPct ? ` · ${deltaPct}%` : ''}). Generating…`
            : `Brief created for "${brief.targetKeyword}". Generating article…`
        );
      } catch (hydrateError) {
        toast.error(
          hydrateError instanceof Error
            ? hydrateError.message
            : 'Failed to create a brief from Hub & Spoke.'
        );
      }
    })();
  }, [briefs, isProjectLoading, projectId, searchParams]);

  useEffect(() => {
    const bulkImportParam = searchParams.get('bulkImport')?.trim() ?? '';
    if (bulkImportParam !== 'hub-spoke' || isProjectLoading || !projectId.trim()) {
      return;
    }

    const bulkImportKey = `${projectId}:bulk`;
    if (hubSpokeBulkImportKeys.has(bulkImportKey)) {
      return;
    }
    hubSpokeBulkImportKeys.add(bulkImportKey);

    const spokes = consumeHubSpokeBulkImport();
    if (!spokes?.length) {
      toast.error('No cluster articles were found for bulk import.');
      return;
    }

    void (async () => {
      try {
        const createdBriefs = await createHubSpokeBriefs(spokes, projectId);
        if (!createdBriefs.length) {
          toast.error('No drafts could be created from the selected clusters.');
          return;
        }

        setBriefs(prev => {
          const existingIds = new Set(prev.map(brief => brief.id));
          const fresh = createdBriefs.filter(brief => !existingIds.has(brief.id));
          return [...fresh, ...prev];
        });

        const firstBrief = createdBriefs[0];
        setSelection({ type: 'brief', briefId: firstBrief.id });
        setActiveArticle(null);
        setDraftContent('');
        setEditorTitle(firstBrief.targetKeyword);
        setSeoTitle('');
        setMetaDescription('');

        toast.success(
          `${createdBriefs.length} article${createdBriefs.length === 1 ? '' : 's'} imported from Topical Authority Studio.`
        );
      } catch (bulkImportError) {
        toast.error(
          bulkImportError instanceof Error
            ? bulkImportError.message
            : 'Failed to import cluster articles from Hub & Spoke.'
        );
      }
    })();
  }, [isProjectLoading, projectId, searchParams]);

  useEffect(() => {
    const bulkImportParam = searchParams.get('bulkImport')?.trim() ?? '';
    if (bulkImportParam !== 'silo-builder' || isProjectLoading || !projectId.trim()) {
      return;
    }

    const bulkImportKey = `${projectId}:silo-bulk`;
    if (siloBuilderBulkImportKeys.has(bulkImportKey)) {
      return;
    }
    siloBuilderBulkImportKeys.add(bulkImportKey);

    const nodes = consumeSiloBuilderBulkImport();
    if (!nodes?.length) {
      toast.error('No silo nodes were found for bulk import.');
      return;
    }

    void (async () => {
      try {
        const createdBriefs = await createSiloBuilderBriefs(nodes, projectId);
        if (!createdBriefs.length) {
          toast.error('No drafts could be created from the selected silo nodes.');
          return;
        }

        setBriefs(prev => {
          const existingIds = new Set(prev.map(brief => brief.id));
          const fresh = createdBriefs.filter(brief => !existingIds.has(brief.id));
          return [...fresh, ...prev];
        });

        const firstBrief = createdBriefs[0];
        setSelection({ type: 'brief', briefId: firstBrief.id });
        setActiveArticle(null);
        setDraftContent('');
        setEditorTitle(firstBrief.targetKeyword);
        setSeoTitle('');
        setMetaDescription('');

        toast.success(
          `${createdBriefs.length} brief${createdBriefs.length === 1 ? '' : 's'} imported from Silo Builder.`
        );
      } catch (bulkImportError) {
        toast.error(
          bulkImportError instanceof Error
            ? bulkImportError.message
            : 'Failed to import briefs from Silo Builder.'
        );
      }
    })();
  }, [isProjectLoading, projectId, searchParams]);

  useEffect(() => {
    const pendingBriefId = pendingAutoGenerateBriefIdRef.current;
    if (!pendingBriefId) {
      return;
    }

    if (hubSpokeAutoGeneratedBriefIds.has(pendingBriefId)) {
      pendingAutoGenerateBriefIdRef.current = null;
      setAwaitingAutoGenerate(false);
      return;
    }

    if (selection?.type !== 'brief' || selection.briefId !== pendingBriefId) {
      return;
    }

    const brief = briefs.find(item => item.id === pendingBriefId);
    if (!brief) {
      return;
    }

    if (activeArticle || getLatestArticle(brief)) {
      pendingAutoGenerateBriefIdRef.current = null;
      setAwaitingAutoGenerate(false);
      return;
    }

    if (isGenerating || generationInFlightRef.current) {
      return;
    }

    hubSpokeAutoGeneratedBriefIds.add(pendingBriefId);
    pendingAutoGenerateBriefIdRef.current = null;
    setAwaitingAutoGenerate(false);
    void handleGenerateArticle();
  }, [activeArticle, briefs, isGenerating, selection]);

  async function handleGenerateArticle() {
    if (!selectedBriefId) {
      toast.error('Select a content brief first.');
      return;
    }

    if (!projectId.trim()) {
      toast.error('Select a project before generating an article.');
      return;
    }

    if (generationInFlightRef.current || isGenerating) {
      return;
    }

    generationInFlightRef.current = true;
    setIsGenerating(true);

    try {
      const response = await fetch('/api/generate-article', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ briefId: selectedBriefId }),
      });

      const payload = await response.json().catch(() => ({}));

      if (!response.ok) {
        const rawMessage =
          typeof payload === 'object' && payload !== null && 'error' in payload
            ? String(payload.error)
            : 'Article generation failed. Please try again.';

        let message = rawMessage;
        if (rawMessage.includes('503') || rawMessage.includes('high demand')) {
          message =
            'The AI model is temporarily overloaded. Please wait a moment and click Regenerate Article.';
        }

        throw new Error(message);
      }

      const parsed = parseGeneratedArticleResponse(
        payload,
        selectedBrief?.targetKeyword || ''
      );

      if (!parsed) {
        throw new Error('Article generation returned invalid data.');
      }

      const { article, seoTitle: generatedSeoTitle, metaDescription: generatedMetaDescription } =
        parsed;

      const optimizedMetaDescription = await ensureGeoOptimizedMetaDescription({
        targetKeyword: selectedBrief?.targetKeyword || '',
        seoTitle: generatedSeoTitle,
        articleContent: article.content,
        briefId: selectedBriefId,
        currentMeta: generatedMetaDescription,
      });

      setActiveArticle(article);
      setEditorTitle(article.title);
      applyGeneratedFieldsToEditor(
        {
          content: article.content,
          seoTitle: generatedSeoTitle,
          metaDescription: optimizedMetaDescription,
        },
        {
          setDraftContent,
          setSeoTitle,
          setMetaDescription,
          setLastSavedSnapshot: snapshot => {
            lastSavedSnapshotRef.current = snapshot;
          },
        }
      );
      syncBriefArticleState(selectedBriefId, article);
      setSaveStatus('unsaved');

      let draftIdForSave = historyId;
      if (!draftIdForSave && selectedBrief) {
        draftIdForSave = await loadHistoryIdForBrief(selectedBrief);
      }

      void saveDraft({
        silent: true,
        contentOverride: article.content,
        seoTitleOverride: generatedSeoTitle,
        metaDescriptionOverride: optimizedMetaDescription,
        draftIdOverride: draftIdForSave,
        articleIdOverride: article.id,
      });
      toast.success('Article generated successfully.');
    } catch (generateError) {
      toast.error(
        generateError instanceof Error
          ? generateError.message
          : 'Article generation failed. Please try again.'
      );
    } finally {
      generationInFlightRef.current = false;
      setIsGenerating(false);
      setAwaitingAutoGenerate(false);
    }
  }

  useEffect(() => {
    if (!isEditorActive) {
      return;
    }

    const currentSnapshot = createDraftSnapshot(draftContent, seoTitle, metaDescription);
    if (draftSnapshotsEqual(currentSnapshot, lastSavedSnapshotRef.current)) {
      return;
    }

    setSaveStatus(current => (current === 'saving' ? current : 'unsaved'));
  }, [draftContent, seoTitle, metaDescription, isEditorActive]);

  useEffect(() => {
    if (!isEditorActive || suppressAutoSaveRef.current || !isDirty || isGenerating) {
      return;
    }

    const currentSnapshot = createDraftSnapshot(
      debouncedDraftContent,
      debouncedSeoTitle,
      debouncedMetaDescription
    );
    if (draftSnapshotsEqual(currentSnapshot, lastSavedSnapshotRef.current)) {
      return;
    }

    void saveDraft({
      silent: true,
      contentOverride: debouncedDraftContent,
      seoTitleOverride: debouncedSeoTitle,
      metaDescriptionOverride: debouncedMetaDescription,
    });
  }, [
    debouncedDraftContent,
    debouncedMetaDescription,
    debouncedSeoTitle,
    isDirty,
    isEditorActive,
    isGenerating,
    saveDraft,
  ]);

  async function handleSaveDraft() {
    await saveDraft({ silent: false });
  }

  async function copyText(text: string, successMessage: string) {
    try {
      await navigator.clipboard.writeText(text);
      toast.success(successMessage);
    } catch {
      toast.error('Unable to copy to clipboard.');
    }
  }

  async function handleExportArticle(format: ArticleExportFormat) {
    if (!draftContent.trim()) {
      toast.error('No article content available to export.');
      return;
    }

    const exportName = getExportNameSource(editorTitle, activeArticle, selectedBrief);
    const filename = buildExportFilename(exportName, format);

    setIsExporting(true);

    try {
      if (format === 'md') {
        const blob = new Blob([draftContent], { type: 'text/markdown;charset=utf-8' });
        triggerFileDownload(blob, filename);
        toast.success('Markdown file downloaded.');
        return;
      }

      if (format === 'txt') {
        const plainText = markdownToPlainText(draftContent);
        const blob = new Blob([plainText], { type: 'text/plain;charset=utf-8' });
        triggerFileDownload(blob, filename);
        toast.success('Text file downloaded.');
        return;
      }

      const response = await fetch('/api/export-docx', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          markdown: draftContent,
          title: exportName,
        }),
      });

      if (!response.ok) {
        const payload = await response.json().catch(() => ({}));
        const message =
          typeof payload === 'object' && payload !== null && 'error' in payload
            ? String(payload.error)
            : 'DOCX export failed. Please try again.';
        throw new Error(message);
      }

      const docxBlob = await response.blob();
      triggerFileDownload(docxBlob, filename);
      toast.success('Word document downloaded.');
    } catch (exportError) {
      toast.error(
        exportError instanceof Error ? exportError.message : 'Export failed. Please try again.'
      );
    } finally {
      setIsExporting(false);
    }
  }

  function renderDraftsSidebar(onItemSelect?: () => void) {
    return (
      <>
        <div className="border-b border-border px-5 py-5">
          <div className="flex items-center gap-2.5">
            <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-emerald-500/10 ring-1 ring-emerald-500/30">
              <PenLine className="h-4.5 w-4.5 text-emerald-400" size={18} />
            </div>
            <div>
              <div className="inline-flex items-center gap-1.5 rounded-full border border-emerald-500/30 bg-emerald-500/10 px-2 py-0.5 text-[10px] font-medium text-emerald-300">
                Article Studio
              </div>
              <p className="mt-1 text-xs text-muted-foreground">{briefs.length} saved briefs</p>
            </div>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto p-3">
          <Button
            type="button"
            className="mb-4 h-10 w-full bg-emerald-600 text-sm font-semibold shadow-sm hover:bg-emerald-500"
            onClick={() => {
              setIsCreateDialogOpen(true);
              onItemSelect?.();
            }}
          >
            <Plus className="mr-2 h-4 w-4" />
            New Article
          </Button>

          {standaloneDrafts.length > 0 ? (
            <div className="mb-5">
              <p className="mb-2 px-1 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
                My Drafts
              </p>
              <ul className="space-y-1.5">
                {standaloneDrafts.map(entry => (
                  <DraftHistoryListItem
                    key={entry.id}
                    entry={entry}
                    isActive={
                      selection?.type === 'standalone' && selection.historyId === entry.id
                    }
                    isDeleting={deletingDraftId === entry.id}
                    onSelect={() => {
                      void handleSelectStandaloneDraft(entry.id);
                      onItemSelect?.();
                    }}
                    onDelete={id => void handleDeleteDraft(id)}
                  />
                ))}
              </ul>
            </div>
          ) : null}

          <p className="mb-2 px-1 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
            Saved Briefs
          </p>

          {briefs.length === 0 ? (
            <div className="rounded-lg border border-dashed border-border bg-muted/60 px-4 py-8 text-center">
              <FileText className="mx-auto mb-3 h-8 w-8 text-muted-foreground/40" />
              <p className="text-sm font-medium text-muted-foreground">No saved briefs yet</p>
              <p className="mt-1 text-xs text-muted-foreground">
                Create a new article above, or generate a brief from Page Optimizer.
              </p>
            </div>
          ) : (
            <ul className="space-y-1.5">
              {briefs.map(brief => (
                <SavedBriefListItem
                  key={brief.id}
                  brief={brief}
                  isActive={selection?.type === 'brief' && selection.briefId === brief.id}
                  isDeleting={deletingBriefId === brief.id}
                  onSelect={() => {
                    void handleSelectBrief(brief.id);
                    onItemSelect?.();
                  }}
                  onDelete={id => void handleDeleteBrief(id)}
                />
              ))}
            </ul>
          )}
        </div>
      </>
    );
  }

  function renderSplitWorkspaceEditor() {
    return (
      <>
        <div className="shrink-0 border-b border-border px-4 py-2 text-xs font-medium text-muted-foreground">
          Markdown Editor
        </div>
        <div className="min-h-0 flex-1 overflow-y-auto">
          <textarea
            value={draftContent}
            onChange={event => setDraftContent(event.target.value)}
            rows={Math.max(24, draftContent.split('\n').length + 2)}
            className="block min-h-full w-full max-w-full min-w-0 resize-none border-0 bg-card p-4 font-mono text-sm leading-relaxed text-foreground outline-none focus:ring-0"
            spellCheck={false}
          />
        </div>
      </>
    );
  }

  function renderSplitWorkspacePreview() {
    return (
      <>
        <div className="flex shrink-0 items-center gap-1.5 border-b border-border px-4 py-2 text-xs font-medium text-muted-foreground">
          <Eye className="h-3.5 w-3.5" />
          Live Preview
        </div>
        <div className="min-h-0 flex-1 overflow-y-auto bg-card p-6">
          <div className="article-markdown-preview w-full max-w-full min-w-0 break-words">
            <ReactMarkdown>{draftContent}</ReactMarkdown>
          </div>
        </div>
      </>
    );
  }

  return (
    <div className="flex h-full min-h-0 w-full flex-1 flex-col overflow-hidden md:flex-row">
      <aside className="hidden shrink-0 overflow-y-auto border-r border-border bg-card md:flex md:w-72 md:flex-col">
        {renderDraftsSidebar()}
      </aside>

      <Sheet open={mobileSidebarOpen} onOpenChange={setMobileSidebarOpen}>
        <SheetContent
          side="left"
          className="w-72 max-w-[85vw] border-r border-border p-0 [&>button]:hidden"
        >
          <SheetTitle className="sr-only">Drafts and Briefs</SheetTitle>
          <div className="flex h-full flex-col bg-card">{renderDraftsSidebar(() => setMobileSidebarOpen(false))}</div>
        </SheetContent>
      </Sheet>

      <CreateArticleDialog
        open={isCreateDialogOpen}
        onOpenChange={setIsCreateDialogOpen}
        onStartBlank={handleStartBlankDraft}
        onQuickGenerate={handleQuickGenerateDraft}
      />

      <div className="flex min-h-0 min-w-0 flex-1 flex-col overflow-hidden">
        <div className="flex shrink-0 items-center border-b border-border bg-card px-4 py-3 md:hidden">
          <Button
            type="button"
            variant="outline"
            size="sm"
            className="w-full justify-center"
            onClick={() => setMobileSidebarOpen(true)}
          >
            <FolderOpen className="mr-2 h-4 w-4" />
            View Drafts & Briefs
          </Button>
        </div>

        <main className="min-w-0 w-full flex-1 overflow-x-hidden overflow-y-auto">
          <div className="sticky top-0 z-10 flex shrink-0 items-center gap-2 border-b border-border bg-card/95 px-4 py-2 backdrop-blur sm:px-6">
            <Tabs
              value={studioMode}
              onValueChange={value => setStudioMode(value as ArticleStudioMode)}
            >
              <TabsList className="h-8">
                <TabsTrigger value="classic" className="text-xs">
                  Classic Studio
                </TabsTrigger>
                <TabsTrigger value="gap-analysis" className="text-xs">
                  Gap Analysis
                </TabsTrigger>
              </TabsList>
            </Tabs>
          </div>

          {studioMode === 'gap-analysis' ? (
            <QueryProvider>
              <div className="h-[calc(100vh-8rem)] min-h-[560px]">
                <GapAnalysisWorkspace
                  key={gapWorkspaceKey}
                  briefId={selectedBriefId}
                  articleId={activeArticle?.id ?? null}
                  onDraftSaved={() => void refreshHistory()}
                />
              </div>
            </QueryProvider>
          ) : (
          <div className="min-h-full w-full max-w-full p-4 sm:p-8">
          {!selection ? (
            <Card className="flex min-h-[480px] w-full max-w-full items-center justify-center border-dashed border-border bg-card/80 shadow-sm">
              <CardContent className="py-16 text-center">
                <Sparkles className="mx-auto mb-4 h-10 w-10 text-emerald-400/60" />
                <p className="text-sm font-medium text-muted-foreground">Start writing in Article Studio</p>
                <p className="mt-1 text-sm text-muted-foreground">
                  Create a blank draft, use Quick AI Writer, or open a saved brief from the sidebar.
                </p>
                <Button
                  type="button"
                  className="mt-6 w-full bg-emerald-600 hover:bg-emerald-500 sm:w-auto"
                  onClick={() => setIsCreateDialogOpen(true)}
                >
                  <Plus className="mr-2 h-4 w-4" />
                  New Article
                </Button>
              </CardContent>
            </Card>
          ) : isGenerating || isQuickGenerating || awaitingAutoGenerate ? (
            <div className="space-y-6">
              <div>
                <h2 className="text-xl font-semibold text-foreground">
                  {editorTitle || selectedBrief?.targetKeyword || 'New Article'}
                </h2>
                <p className="mt-1 text-sm text-muted-foreground">
                  {isQuickGenerating
                    ? 'Gemini is writing your article from your inputs…'
                    : awaitingAutoGenerate
                      ? 'Preparing your Hub & Spoke brief and starting generation…'
                      : 'Gemini is drafting your GEO-optimized article…'}
                </p>
              </div>
              <GenerationSkeleton />
            </div>
          ) : selection.type === 'brief' && !activeArticle && selectedBrief ? (
            <div className="mx-auto max-w-3xl space-y-6">
              <div>
                <p className="text-xs font-semibold uppercase tracking-wide text-emerald-600 dark:text-emerald-300">
                  Content Brief
                </p>
                <h2 className="mt-1 text-2xl font-semibold text-foreground">
                  {selectedBrief.targetKeyword}
                </h2>
                <p className="mt-1 break-all text-sm text-muted-foreground">{selectedBrief.targetUrl}</p>
              </div>

              <Card className="border-border shadow-sm">
                <CardHeader>
                  <CardTitle className="text-base">Brief Summary</CardTitle>
                  <CardDescription>
                    Created {format(new Date(selectedBrief.createdAt), 'MMM d, yyyy · h:mm a')}
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <p className="text-sm leading-relaxed text-muted-foreground">
                    {truncateBriefSummary(selectedBrief.content)}
                  </p>
                  <div className="mt-4 max-h-64 overflow-y-auto rounded-lg border border-border bg-muted/50 p-4">
                    <pre className="whitespace-pre-wrap font-sans text-xs leading-relaxed text-muted-foreground">
                      {selectedBrief.content}
                    </pre>
                  </div>
                </CardContent>
              </Card>

              <Button
                type="button"
                size="lg"
                className="h-12 w-full bg-emerald-600 text-base hover:bg-emerald-500 sm:w-auto sm:px-8"
                onClick={handleGenerateArticle}
                disabled={isGenerating || awaitingAutoGenerate}
              >
                {isGenerating ? (
                  <Loader2 className="mr-2 h-5 w-5 animate-spin" />
                ) : (
                  <Sparkles className="mr-2 h-5 w-5" />
                )}
                Generate AI Article
              </Button>
            </div>
          ) : isEditorActive ? (
            <div className="w-full max-w-full min-w-0 space-y-6">
              <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
                <div className="min-w-0 w-full max-w-full">
                  <p className="text-xs font-semibold uppercase tracking-wide text-emerald-600 dark:text-emerald-300">
                    {isStandaloneEditor ? 'Manual Draft' : 'Article Draft'}
                  </p>
                  <h2 className="mt-1 truncate text-2xl font-semibold text-foreground">
                    {editorTitle || activeArticle?.title || 'Untitled Draft'}
                  </h2>
                  <p className="mt-1 text-sm text-muted-foreground">
                    {isStandaloneEditor
                      ? 'Standalone draft · edits auto-save to history'
                      : `Last updated ${format(
                          new Date(activeArticle?.updatedAt ?? activeArticle?.createdAt ?? Date.now()),
                          'MMM d, yyyy · h:mm a'
                        )}`}
                  </p>
                </div>

                <div className="flex w-full max-w-full min-w-0 flex-col gap-2 sm:flex-row sm:flex-wrap sm:items-center">
                  <SaveStatusIndicator status={saveStatus} />
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    className="w-full sm:w-auto"
                    onClick={() => void handleSaveDraft()}
                    disabled={isSaving || !isDirty || isGenerating}
                  >
                    {isSaving ? (
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    ) : (
                      <Save className="mr-2 h-4 w-4" />
                    )}
                    Save Draft
                  </Button>
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    className="w-full sm:w-auto"
                    onClick={() => copyText(draftContent, 'Markdown copied to clipboard.')}
                  >
                    <Copy className="mr-2 h-4 w-4" />
                    Copy Markdown
                  </Button>
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <Button
                        type="button"
                        variant="outline"
                        size="sm"
                        className="w-full sm:w-auto"
                        disabled={isExporting || !draftContent.trim()}
                      >
                        {isExporting ? (
                          <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                        ) : (
                          <Download className="mr-2 h-4 w-4" />
                        )}
                        Export
                        <ChevronDown className="ml-2 h-4 w-4" />
                      </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align="end">
                      <DropdownMenuItem onClick={() => void handleExportArticle('md')}>
                        Export as .md
                      </DropdownMenuItem>
                      <DropdownMenuItem onClick={() => void handleExportArticle('txt')}>
                        Export as .txt
                      </DropdownMenuItem>
                      <DropdownMenuItem onClick={() => void handleExportArticle('docx')}>
                        Export as .docx
                      </DropdownMenuItem>
                    </DropdownMenuContent>
                  </DropdownMenu>
                  <Button
                    type="button"
                    size="sm"
                    className="w-full bg-emerald-600 hover:bg-emerald-500 sm:w-auto"
                    onClick={() => setIsWordPressDialogOpen(true)}
                    disabled={!draftContent.trim()}
                  >
                    <Upload className="mr-2 h-4 w-4" />
                    Publish to WordPress
                  </Button>
                  {!isStandaloneEditor ? (
                    <Button
                      type="button"
                      variant="outline"
                      size="sm"
                      className="w-full sm:w-auto"
                      onClick={handleGenerateArticle}
                      disabled={isGenerating}
                    >
                      {isGenerating ? (
                        <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      ) : (
                        <RefreshCw className="mr-2 h-4 w-4" />
                      )}
                      Regenerate Article
                    </Button>
                  ) : null}
                </div>
              </div>

              <div className="grid w-full max-w-full min-w-0 gap-4 sm:grid-cols-2">
                <EditableMetadataField
                  label="SEO Title"
                  value={seoTitle}
                  onChange={setSeoTitle}
                  placeholder="Enter SEO Title..."
                  onCopy={() => {
                    if (seoTitle.trim()) {
                      void copyText(seoTitle, 'SEO title copied.');
                    }
                  }}
                />
                <EditableMetadataField
                  label="Meta Description"
                  value={metaDescription}
                  onChange={setMetaDescription}
                  placeholder="Enter Meta Description..."
                  multiline
                  onCopy={() => {
                    if (metaDescription.trim()) {
                      void copyText(metaDescription, 'Meta description copied.');
                    }
                  }}
                />
              </div>

              <Card className="w-full max-w-full min-w-0 overflow-hidden border-border shadow-sm">
                <CardHeader className="border-b border-border bg-muted/50 py-3">
                  <div className="flex min-w-0 flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                    <div className="flex min-w-0 items-center gap-3">
                      <CardTitle className="text-sm font-medium text-foreground">
                        Interactive Workspace
                      </CardTitle>
                      <SaveStatusIndicator status={saveStatus} />
                    </div>
                    <Tabs
                      value={workspaceTab}
                      onValueChange={value => setWorkspaceTab(value as typeof workspaceTab)}
                    >
                      <TabsList className="h-8">
                        <TabsTrigger value="split" className="text-xs">
                          Split
                        </TabsTrigger>
                        <TabsTrigger value="edit" className="text-xs">
                          Edit
                        </TabsTrigger>
                        <TabsTrigger value="preview" className="text-xs">
                          Preview
                        </TabsTrigger>
                      </TabsList>
                    </Tabs>
                  </div>
                </CardHeader>
                <CardContent className="w-full max-w-full min-w-0 p-0">
                  {workspaceTab === 'split' ? (
                    <>
                      <div className="flex min-h-[520px] flex-col md:hidden">
                        <div className="flex min-h-[280px] min-w-0 flex-1 flex-col overflow-hidden border-b border-border">
                          {renderSplitWorkspaceEditor()}
                        </div>
                        <div className="flex min-h-[280px] min-w-0 flex-1 flex-col overflow-hidden">
                          {renderSplitWorkspacePreview()}
                        </div>
                      </div>
                      <div className="hidden h-[calc(100vh-280px)] min-h-[520px] md:flex md:flex-col">
                        <ResizablePanelGroup
                          direction="horizontal"
                          className="h-full min-h-0 w-full"
                        >
                          <ResizablePanel defaultSize={50} minSize={30} className="min-h-0">
                            <div className="flex h-full min-h-0 flex-col overflow-hidden">
                              {renderSplitWorkspaceEditor()}
                            </div>
                          </ResizablePanel>
                          <ResizableHandle withHandle />
                          <ResizablePanel defaultSize={50} minSize={30} className="min-h-0">
                            <div className="flex h-full min-h-0 flex-col overflow-hidden">
                              {renderSplitWorkspacePreview()}
                            </div>
                          </ResizablePanel>
                        </ResizablePanelGroup>
                      </div>
                    </>
                  ) : workspaceTab === 'edit' ? (
                    <textarea
                      value={draftContent}
                      onChange={event => setDraftContent(event.target.value)}
                      className="min-h-[520px] w-full max-w-full min-w-0 resize-none border-0 bg-card p-4 font-mono text-sm leading-relaxed text-foreground outline-none focus:ring-0"
                      spellCheck={false}
                    />
                  ) : (
                    <div className="h-[calc(100vh-280px)] min-h-[520px] w-full max-w-full min-w-0 overflow-y-auto overflow-x-hidden bg-card p-6">
                      <div className="article-markdown-preview w-full max-w-full min-w-0 break-words">
                        <ReactMarkdown>{draftContent}</ReactMarkdown>
                      </div>
                    </div>
                  )}
                </CardContent>
              </Card>

              <PublishWordPressDialog
                open={isWordPressDialogOpen}
                onOpenChange={setIsWordPressDialogOpen}
                title={editorTitle || activeArticle?.title || 'Untitled Draft'}
                content={draftContent}
                siloSync={
                  siloLink?.siloNodeId
                    ? {
                        siloNodeId: siloLink.siloNodeId,
                        articleStudioHistoryId: siloLink.articleStudioHistoryId ?? historyId,
                      }
                    : undefined
                }
              />
            </div>
          ) : null}
          </div>
          )}
        </main>
      </div>
    </div>
  );
}
